### ISSUE TITLE
Is the client compatible with Flutter?

### ISSUE THREAD

**Issue by alexvinidiktov** [jwashin/jsonrpc2-dart#6]
I'm looking for a jsonrpc2 client for Flutter that supports http transport.

Is this library compatible with Flutter?

**Comment by jwashin** [comment]
I'm playing with Flutter right now, and am pleased to see that the
io_client works ok in Android. Actually, I think the jsonrpc_client
(original http only client) works under universal_html for web. I'll need
to update docs and stuff soon. Also, custom headers were necessary for my
current project (jwt headers for auth), so there should be an update in the
near future. I wouldn't use the server package in browser/JavaScript
because the dispatcher uses mirrors.

Jim Washington

**Comment by alexvinidiktov** [comment]
Jim, that's awesome!

I also need custom headers for jwt auth in my app.

I'm looking forward to the update!

**Comment by alexvinidiktov** [comment]
Any news?

**Comment by jwashin** [comment]
Yes. I've decided to modernize and reorganize some, while I'm at it. Null
safety. A dispatcher that uses reflectable instead of mirrors. I'll push
something to github later today.

Jim

**Comment by jwashin** [comment]
3.0 is released today on github
